### ISSUE TITLE
Mapsui and Gmap demo don't show anything

### ISSUE THREAD

**Issue by charlenni** [AliFlux/VectorTileRenderer#1]
Thank you for this nice project. Could be very helpfull.

I downloaded it and try to start it, but Mapsui and GmapNet don't show any data. Debuged Mapsui version. Opens MBtiles file correct, but when running it, than I get many `Exception thrown: 'System.IO.DirectoryNotFoundException' in mscorlib.dll`

Any idea?

**Comment by AliFlux** [comment]
I think the `.gitignore` somehow ignored the cache directory as well. Try making a folder named `tile-cache` right next to your solution (`.sln`) file.

**Comment by AliFlux** [comment]
I've added a check to the cache directory. Please check it and let me know if that works.

**Comment by AliFlux** [comment]
Yeah the symbols are missing at the moment. But I'll try to get it integrated in the next week.

Can you please share your progress? I'm excited to see some on-the-fly rendering.

**Comment by charlenni** [comment]
You could find it at [here](https://github.com/charlenni/Mapsui.VectorTiles). Discussion is in Mapsui #152.
