### ISSUE TITLE
Rendering PBF from Azure Maps only shows background

### ISSUE THREAD

**Issue by Skleni** [AliFlux/VectorTileRenderer#12]
Hi,

I tried using your library to render a vector tile from [Azure Maps](https://docs.microsoft.com/en-us/rest/api/maps/render/getmaptile), but I only get an empty image with a background color. I debugged through the code and the condition in line 228 of https://github.com/AliFlux/VectorTileRenderer/blob/master/VectorTileRenderer/Renderer.cs is never true. Do you have any ideas? I can provide the PBF file if that helps.

Thank you!

**Comment by AliFlux** [comment]
Azure Map tiles are only compatible with the Azure Map styles. Make sure that you're using appropriate style as well. If you are, please share a project file so that I can debug the issue in detail.

**Comment by Skleni** [comment]
Okay, thanks! I'll have to figure out a way to get these styles and try that.

**Comment by rbrundritt** [comment]
To help point you in the right direction, the road map tiles in Azure Maps come from TomTom. The source layers in the tiles are documented here: https://developer.tomtom.com/maps-api/maps-api-documentation-vector/tile

The Azure Maps web SDK currently breaks the styles into three layer groups and uses 3 files. If you watch the network traffic, look for base.json, transit.json and labels.json.

**Comment by Skleni** [comment]
Thanks!
