### ISSUE TITLE
loading vector tiles 

### ISSUE THREAD

**Issue by Kayumiy** [AliFlux/VectorTileRenderer#15]
There are 3 kinds of files:

.dbf
.shp
.shx
 
Is It possible to load this data files by using your project?
I have seen these files:
.pbf, 
.mbtiles, 

But I did not seen 

.dbf
.shp
.shx

files in your project.

Thank You

**Comment by AliFlux** [comment]
Hi.

pbf and mbtiles are `processed vector tiles`, while shp, kml, geojson, etc are `raw vector data`. To show shapefile into your project, use a map control that can show those shapefiles (such as SharpMap).

If your raw vector data files are too big and dense to show directly, you can use [tippecanoe](https://github.com/mapbox/tippecanoe) to convert that into processed vector tiles, and then show them on your client. But it's a bit of a difficult thing to do, so i'd recommend the first method

**Comment by Kayumiy** [comment]
There are 3 projects in this repository:
1. GMap>demo.WinForms
2. Mapsui.Demo.WPF
3. Static.Demo.WPF

When I run these projects, all of them shows same UI result even though they are different UI.

![image](https://user-images.githubusercontent.com/22438366/81263834-5df5fa00-907b-11ea-9c05-0b5d82e205f6.png)

I have my own vector tiles should be load in this project. I don't know how to load my map data instead of yours. Can you guide me please?

**Comment by charlenni** [comment]
I assume, that you misunderstand what VectorTileRenderer does. It isn't a mapping library. It converts vector map data into raster tiles. This tiles than could be displayed with GMap or Mapsui. If you want to display your own data on a map, you should look into GMap or Mapsui.

**Comment by Kayumiy** [comment]
![image](https://user-images.githubusercontent.com/22438366/81270562-e11c4d80-9085-11ea-84fe-91319d8a41ca.png)

I tried to use gMap but it shows .gmdb file.
I need library which can load shapefile (.shp, .shx, .dbf)

**Comment by charlenni** [comment]
It seems, that Mapsui could handle SHP files. See the [shapefile sample](https://github.com/Mapsui/Mapsui/blob/master/Samples/Mapsui.Samples.Common.Desktop/ShapefileSample.cs).
