### ISSUE TITLE
map rendering using Pbf file

### ISSUE THREAD

**Issue by anushabasavaraj92** [AliFlux/VectorTileRenderer#16]
Hi, 

There is a sample on how to render the map from mbtiles in a wpf project. Is there a similar way to render the map from pbf file in wpf project?

**Comment by AliFlux** [comment]
Hi, 

Check out the Static.Demo.WPF project, it renders map from pbf file

**Comment by anushabasavaraj92** [comment]
I tried the ShowPbf function  with another pbf file and I am getting an exception error "Tag out of bounds" , when the function calls Render function. I am not sure what is the reason for it.

**Comment by AliFlux** [comment]
Can you share the pbf file here? And the code that you used as well

**Comment by anushabasavaraj92** [comment]
I have used the pbf file downloaded from below link:

http://download.geofabrik.de/asia/india.html

I copied the downloaded file, "India-latest.osm.pbf" to the tiles folder of the project and modified the MainWindow() constructor as below:

        public MainWindow()
        {
            InitializeComponent();

            showPbf(mainDir + @"tiles/india-latest.osm.pbf", mainDir + @"styles/basic-style.json", 14);
        }

**Comment by AliFlux** [comment]
You're using a different type of pbf. The dataset available at geofabrik is raw osm vector data, not the tiled vector data.

You can download vector tiles at https://openmaptiles.org/

**Comment by anushabasavaraj92** [comment]
Is there a way to render the tiled vector data from the raw osm vector data?
The below link only has mbtiles format.
Regards,Anusha

Sent from Yahoo Mail on Android 
 
  On Sat, 4 Jul 2020 at 12:29 am, Ali Ashraf<notifications@github.com> wrote:   


You're using a different type of pbf. The dataset available at geofabrik is raw osm vector data, not the tiled vector data.

You can download vector tiles at https://openmaptiles.org/

**Comment by AliFlux** [comment]
The raw vector data (.pbf at geofabrik) is converted to tiled vector data (.mbtiles at openmaptiles) using software such as tilelive and tippecanoe.

You can use the mbtiles with the VectorTileRenderer directly. Check out the examples in the solution

**Comment by anushabasavaraj92** [comment]
Thank you. I have successfully used mbtiles. I had one more query, Is there a way to modify disputed international borders according to the country in mbtiles?

Sent from Yahoo Mail on Android 
 
  On Sat, 4 Jul 2020 at 1:38 am, Ali Ashraf<notifications@github.com> wrote:   


The raw vector data (.pbf at geofabrik) is converted to tiled vector data (.mbtiles at openmaptiles) using software such as tilelive and tippecanoe.

You can use the mbtiles with the VectorTileRenderer directly. Check out the examples in the solution

**Comment by AliFlux** [comment]
@anushabasavaraj92 it is possible. But you'll have to [modify the style.json accordingly](https://www.maptiler.com/news/2020/01/disputed-borders-in-openmaptiles-3-11/)
