### ISSUE TITLE
Vector Tile Library

### ISSUE THREAD

**Issue by pauldendulk** [AliFlux/VectorTileRenderer#3]
I see you have a reference to Bert Temmes vector tile library but actually use the vector tile library developed by mapbox. What is the reason you switched to the mapbox one? Any problems you ran into?

**Comment by AliFlux** [comment]
I started with Bert's library. But when the project was completed, I did some thorough benchmarking. Apparently the mapbox's vector tile parsing library is considerably faster than Bert's.

**Comment by pauldendulk** [comment]
Okay, thanks for the info. Perhaps Bert's geojson step is taking too much time.

**Comment by AliFlux** [comment]
Or it could be the protobuf-net, the library that is decoding pbf files. Can't say for sure until the profiling is done.

**Comment by pauldendulk** [comment]
Do you know what the mapbox library is using for the decoding? 

Do you know if there are plans to use [msgpacke](https://msgpack.org/) instead of protobuf at some point?

**Comment by AliFlux** [comment]
Mapbox library is doing decoding by itself, without dependencies. And I don't think there are plans to port it from protobuf, because its a pretty stable format and backed by Google.
