### ISSUE TITLE
Cannot Build

### ISSUE THREAD

**Issue by YuryKomar** [AliFlux/VectorTileRenderer#33]
I cannot Build the Project(s) due to old NUGET version used and it say cannot find it on the machine.

Asking, please build it at your end and save here as release.
I need to use vector maps with GMap.NET, your lib very interested to me. Please update and share release DLLs.

Thanks a lot in advance.

**Comment by kezara** [comment]
Hi could you please advise missing packages?

**Comment by YuryKomar** [comment]
The VectorTileRenderer.dll has been compiled successfully. It is good, but it has a lot of other dependecies :((( Sooo many DLLs has to be copied, terrible.

So the case with builds could be closed, I have restrted the PC and tried to re-build and all in order now.
