### ISSUE TITLE
An unhandled exception of type 'System.StackOverflowException' occurred in mscorlib.dll

### ISSUE THREAD

**Issue by Phantamoss** [AliFlux/VectorTileRenderer#8]
Getting an StackOverflowException when trying to use VectorMbTilesProvider for Gmap. Happens at line
>   provider = new VectorTileRenderer.Sources.MbTilesSource(path);

Any ideas what could cause this? Runs without issue in the demo.

**Comment by AliFlux** [comment]
It's probably something related to the mbtiles file. Can you please share it so that I can debug it?

**Comment by AliFlux** [comment]
The US tiles are pretty big so I just downloaded a fresh set of liechtenstein tiles to test the GMap code, and it works perfectly.

Can you please share your code here? So that I can debug that exception.

**Comment by Phantamoss** [comment]
If I use the US tiles on the demo in your source code it works fine. Here you go.

https://github.com/Phantamoss/WpfApp2

**Comment by Phantamoss** [comment]
Need to import skiasharp, and the problem seemed to go away.
The tiles are blank though.
